spring:
  logging:
    level:
      org.springframework.ai: DEBUG
      org.springframework.web.client: DEBUG
  application:
    name: demo-webinar1-no_react
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:4b-it-q4_K_M   # Обязательно в кавычках!
      embedding:
        model: nxbai-embed-large     # Тоже в кавычках — на всякий случай